"""add approved-artifact metadata jsonb to requirements and diagrams

Revision ID: 6132c1ad5321
Revises: 179c9fc350d7
Create Date: 2026-08-18 22:43:23.347400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6132c1ad5321'
down_revision: Union[str, Sequence[str], None] = '179c9fc350d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('requirements', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'metadata')
    op.drop_column('diagrams', 'metadata')
    # ### end Alembic commands ###
