"""add updated_at to sessions for recency ordering

Revision ID: f8f15e1ea742
Revises: 742e4470be4b
Create Date: 2026-09-01 23:08:06.294179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f15e1ea742'
down_revision: Union[str, Sequence[str], None] = '742e4470be4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'updated_at')
    # ### end Alembic commands ###
